### ISSUE TITLE
url_for helper doesn't work for mailto link

### ISSUE THREAD

**Issue by lookis** [hexojs/hexo-util#122]
https://github.com/hexojs/hexo-util/blob/master/lib/url_for.js#L28-L31

it will return origin path when met external link like http://example.com, but will not return origin path for mailto: someone@example.com. and lead to an issue when relative_link was set.

url_for('/category') => /relative_link/category <= OK!
url_for('http://example.com') => http://example.com <= OK!
url_for('mailto:someone@example.com') => /relative_link/mailto:someone@example.com <= Ops!

**Comment by SukkaW** [comment]
There is no better way to fix this. We might need to hardcode some whitelist protocol inside hexo-util, just as one of contributor of nodejs gives: https://github.com/nodejs/node/pull/28482/

https://github.com/nodejs/node/blob/49a5fa0d8b15cc50df833848bfc01d2260930dfd/lib/internal/url.js#L340-L348

**Comment by SukkaW** [comment]
@curbengh Any idea?

In `isExternalLink()` we use `new URL(path)).origin === 'null'` to consider `mailto:` `javascript:` links as an internal link. But when at `url_for` and `full_url_for`, it requires to consider them as an external link.

Currently I only come up with the idea of whitelist protocols.

**Comment by curbengh** [comment]
The [workaround](https://github.com/hexojs/hexo-util/blob/master/lib/url_for.js#L28-L31) is necessary to support path with [a semicolon](https://github.com/hexojs/hexo-util/blob/master/test/url_for.spec.js#L76-L81).

However, since `encodeURL()` never support path with semicolon, I'm ok dropping it from `url_for()` and `full_url_for()`.

I'm assuming `mailto:` is more common than path with semicolon.

**Comment by curbengh** [comment]
When I created https://github.com/hexojs/hexo-util/pull/114, I assumed `url_for()` would only be used for relative url, not data url (like `mailto:`) nor absolute url, which is why I made a leeway to support path with semicolon.

In relation to https://github.com/theme-next/hexo-theme-next/issues/1260, I wonder why  `url_for(mailto:)` exists (my apology, I don't understand `社交栏` and `检查单`). I assume the theme dev also share my assumption.

Btw, this issue is still going to [be fixed](https://github.com/hexojs/hexo-util/pull/130).

**Comment by lookis** [comment]
thx @curbengh 
社交栏 means social account such as facebook or twitter account
检查单 is a check list for user to submit an issue

and I am not the author of theme-next, maybe they wrap every link with url_for :(

**Comment by stevenjoezhang** [comment]
https://github.com/theme-next/hexo-theme-next/blob/45148b265df579977a18bde6a908cf4977a75797/scripts/helpers/next-url.js#L16

theme-next is using a custom helper `next_url`. It is used to generate an `<a>` tag with a custom attributes.
