### ISSUE TITLE
The new code block layout made it difficult to select and copy code without including the line number

### ISSUE THREAD

**Issue by ppoffice** [hexojs/hexo-util#145]
Before the new layout:
I can select **code and code only** by hand or using `clipboard.js`
![image](https://user-images.githubusercontent.com/8849362/69896221-b7a70b00-130a-11ea-96fd-19ba63569dac.png)

After the new layout:
Line number is also selected as each number is within the same line as the code
![image](https://user-images.githubusercontent.com/8849362/69896289-a1e61580-130b-11ea-8b94-2184cd87363b.png)

Related code:
https://github.com/hexojs/hexo-util/blob/master/lib/highlight.js#L45-L55

**Comment by SukkaW** [comment]
Related issue: https://github.com/hexojs/hexo/issues/3884 https://github.com/hexojs/hexo/issues/3913 https://github.com/hexojs/hexo-util/commit/401dde1621331d07ce52caf37c94951bac33ddb7#r36250206

@curbengh @stevenjoezhang @jiangtj

Since it is a serious Breaking Changes that already breaks a lot of theme. I suggest to revert the PR https://github.com/hexojs/hexo-util/pull/132 and release an emergency release of hexo-util & hexo.

**Comment by SukkaW** [comment]
SInce the `prismjs` is already on the roadmap, IMHO we shouldn't bring any changes to current `highlightjs` since it will be deprecated soon.

**Comment by curbengh** [comment]
https://github.com/hexojs/hexo-util/pull/153
